---
  - name: Install NFS Utils
    apt: pkg={{item}} state=latest
    with_items:
      - nfs-common
      - autofs
      - rpcbind

  - name: Ensure rpcbind service is running
    service: name=rpcbind state=started enabled=yes


  - name: Create EFS mount point
    file:
      path: "{{ efs_mount_point }}"
      state: directory
      recurse: yes
      owner: "{{ deploy_user }}"
      group: "{{ deploy_group }}"
      mode: 0755

  - name: mount EFS volume
    mount:
      path: "{{ efs_mount_point }}"
      src:  "{{ efs_volume }}"
      fstype: nfs4
      opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
      state: mounted

  - name: Set permission to deploy
    file:
      path: "{{ efs_mount_point }}"
      recurse: no
      owner: "{{ deploy_user }}"
      group: "{{ deploy_group }}"
