---
  - name: Install Apache 2.4
    apt: name=apache2 state=present update_cache=yes
  - name: Install  PHP Packages
    apt: pkg={{ item }} state=latest
    with_items:
      - "libapache2-mod-fcgid"
  - name: Start and enable Apache service
    service: name=apache2 state=restarted enabled=yes
  - name: enabled modules
    apache2_module: name="{{item}}" state=present
    with_items:
      - proxy_fcgi
      - setenvif
      - actions
      - fcgid
      - expires
      - rewrite
      - fcgid

  - name: a2enmod actions fcgid alias proxy_fcgi
    command: a2enmod actions fcgid alias proxy_fcgi

  - name: a2enmod rewrite expires
    command: a2enmod rewrite expires

  - name: configure vhosts
    template: src=vhost.conf dest=/etc/apache2/sites-available/000-{{domain_name}}.conf owner=root group=root mode=0644

#  - name: Copy ssl vhosts for dev only
#    template: src=vhost_ssl.conf dest=/etc/apache2/sites-available/000-{{domain_name}}-le-ssl.conf owner=root group=root mode=0644

  - name: a2ensite 000-{{domain_name}}.conf
    command: a2ensite 000-{{domain_name}}.conf

  - name: Disable default vhost
    command: a2dissite 000-default.conf

  - name: copy envvars
    template: src=envvars dest=/etc/apache2/envvars owner=root group=root mode=0644
    notify: Restart apache2

  - name: copy Apache Conf
    template: src=apache2conf dest=/etc/apache2/apache2.conf owner=root group=root mode=0644
    notify: Restart apache2
  
  - name: copy .htpasswd file
    template: src=.htpasswd dest=/etc/apache2/.htpasswd owner=root group=root mode=0644
    notify: Restart apache2
  
  - name: create Apache2 document root directory
    file:
      path: /home/deploy/current/
      state: directory
      recurse: yes
      owner: deploy
      group: deploy
      mode: 0755

  - name: create Apache2 document root directory
    file:
      path: /home/deploy/releases/
      state: directory
      recurse: yes
      owner: deploy
      group: deploy
      mode: 0755

  - name: create Apache2 document root directory
    file:
      path: /home/deploy/shared/
      state: directory
      recurse: yes
      owner: deploy
      group: deploy
      mode: 0755

  - name: copy application file
    template: src=configure.j2 dest=/home/deploy/shared/configure.php owner=deploy group=deploy mode=0644
    notify: Restart apache2

  - name: copy application file
    template: src=admincp_configure.j2 dest=/home/deploy/shared/admincp_configure.php owner=deploy group=deploy mode=0644
    notify: Restart apache2

