---
# Add specified repository into sources list.
# always try to use HTTPS. I'm not sure why the nginx folks don't provide it.
  - name: Add apt keys for nginx
    apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

  - name: Add Nginx repository
    apt_repository: repo='deb http://nginx.org/packages/ubuntu/ xenial nginx' state=present filename='nginx' update_cache='yes'

  - name: Install nginx
    apt: name=nginx state=present update_cache=yes cache_valid_time=3600

  - name: remove default site
    file: path=/etc/nginx/sites-enabled/default state=absent

  - name: remove default site
    file: path=/etc/nginx/sites-available/default state=absent

  - name: remove default site in conf
    file: path=/etc/nginx/conf.d/default.conf state=absent

  - name: configure nginx.conf
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644

  - name: configure headers.conf
    template: src=headers.frag dest=/etc/nginx/conf.d/headers.frag owner=root group=root mode=0644

  - name: configure vhosts
    template: src=vhost.conf dest=/etc/nginx/conf.d/{{domain_name}}.conf owner=root group=root mode=0644
  - name: create /opt/redux and /opt/redux/scripts directory
    file:
      path: /home/deploy/public_html
      state: directory
      recurse: yes
      owner: deploy
      group: deploy
      mode: 0755

  - name: config test and restart
    command: nginx -t -c /etc/nginx/nginx.conf
    ignore_errors: True
    register: result

  - name: restart nginx
    service: name=nginx state=restarted enabled=yes
    when: result is success

  - name: Update logroate for nginx
    copy: src=logrotate_nginx dest=/etc/logrotate.d/nginx owner=root group=root mode=0644
