<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.0.2 setup script
 * Date: Mon, 01 Jun 2020 18:40:27 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: okindustrial-dev [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'okindustrial-dev';
$cfg['Servers'][$i]['host'] = '10.20.10.167';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'dbadmindev';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['AllowRoot'] = false;
$cfg['Servers'][$i]['DisableIS'] = true;
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['hide_db'] = 'information_schema|performance_schema|mysql';


$cfg['blowfish_secret'] = '3S~>l1!Nds!,P2[{z@F<!dax?ni(Go}~';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
