#! /bin/bash
# Script to list Instance details from Bastion

REGION="us-east-2"
MGMT_VPC="vpc-07d58d68c9066a863"
DEV_VPC="vpc-0dbec903ad811a160"
#PROD_VPC=" "

echo "Management VPC Instances"
echo "----------------------------"
aws ec2 describe-instances --region "$REGION" --filters Name=vpc-id,Values="$MGMT_VPC" --query 'Reservations[].Instances[].[PrivateIpAddress,InstanceId,Tags[?Key==`Name`].Value[]]' --output text | sed '$!N;s/\n/ /'
echo ""

echo "Development VPC Instances"
echo "----------------------------"
aws ec2 describe-instances --region "$REGION" --filters Name=vpc-id,Values="$DEV_VPC" --query 'Reservations[].Instances[].[PrivateIpAddress,InstanceId,Tags[?Key==`Name`].Value[]]' --output text | sed '$!N;s/\n/ /'
echo ""

#echo "Production VPC Instances"
#echo "----------------------------"
#aws ec2 describe-instances --region "$REGION"  --filters Name=vpc-id,Values="$PROD_VPC" --query 'Reservations[].Instances[].[PrivateIpAddress,InstanceId,Tags[?Key==`Name`].Value[]]' --output text | sed '$!N;s/\n/ /'
#echo ""
