---
- name: Install perl dependencies for EC2 Monitoring
  apt: 
    name: "{{ item }}" 
    state: latest
  with_items:
    - libwww-perl
    - libdatetime-perl

- name: Create Directory for Downloading Cloudwatch Agent
  file:
    path: /usr/local/src
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: no

- name: copy config.json file
  template: src=config.json.j2 dest=/opt/redux/scripts/config.json owner=root group=root mode=0644        

- name: Install cloud watch agent
  template: src=cloudwatch_agent.sh dest=/opt/redux/scripts/cloudwatch_agent.sh owner=root group=root mode=0777

- name: Run cloudwatch script
  shell: /opt/redux/scripts/cloudwatch_agent.sh

