---
- apt: pkg=python3-pip state=latest

- pip: 
    name:
      - boto3
      - boto  
           

- ec2_instance_facts:
    region: us-east-2
    filters:
     "tag:Environment": "{{ env }}"
  register: ec2_info  

- debug:
    msg: "{{ ec2_info.instances | sum(attribute='block_device_mappings', start=[]) | map(attribute='ebs.volume_id') | list }}"
  register: ec2_set
- debug:
    msg: "{{ ec2_info.instances | sum(attribute='block_device_mappings', start=[]) | map(attribute='ebs.volume_id') | list | length }}"

- debug:
    msg: '{{  ec2_set.msg }}' 

- ec2_tag:
    region: us-east-2    
    resource: '{{ item }}'
    state: present
    tags:
     backup: "{{env_backup_tag}}"
  with_items: '{{ ec2_set.msg }}'
