---

  - name: Add ondrej/php PPA
    apt_repository: repo='ppa:ondrej/php' state=present update_cache=yes
  - name: Install php8
    apt: pkg=php8.0 state=latest update_cache=yes cache_valid_time=3600
    tags: [ 'packages' ]
  - name: Install PHP modules
    apt: pkg={{ item }} state=latest
    with_items:
      - php8.0-bz2
      - php8.0-curl
      - php8.0-dom
      - php8.0-fpm
      - php8.0-gd
      - php8.0-mbstring
      - php8.0-mysql
      - php8.0-mysqlnd
      - php8.0-pdo
      - php8.0-sqlite3
      - php8.0-zip
      - php8.0-mcrypt

  - name: Add php-fpm configuration files
    template: src=www.conf.j2 dest=/etc/php/8.0/fpm/pool.d/www.conf owner=root group=root mode=0644
    notify: Restart php8.0-fpm

  - name: Copy  Sourceguardian script
    template: src=sourceguardian.sh dest=/opt/redux/scripts/sourceguardian.sh owner=root group=root mode=0755

  - name: Run sourceguardian script
    shell: /opt/redux/scripts/sourceguardian.sh

  - name: Copy fpm/php.ini file
    template: src=php.ini.j2 dest=/etc/php/8.0/fpm/php.ini owner=root group=root mode=0644
    notify: Restart php8.0-fpm

  - name: Copy cli/php.ini file
    template: src=php.ini.j2 dest=/etc/php/8.0/cli/php.ini owner=root group=root mode=0644
    notify: Restart php8.0-fpm

  - name: Start php-fpm service
    service: name=php8.0-fpm state=started  enabled=yes
